### ISSUE TITLE
Storage data limit

### ISSUE THREAD

**Issue by toshiboy86** [argentlabs/hopper#7]
> The Hopper contract can be used up to 32768 times in total before the Merkle tree fills up and a new contract must be deployed. This corresponds to a tree depth of 15 which was chosen to keep the gas cost of a commitment under 1,000,000 gas.

https://medium.com/argenthq/introducing-hopper-mobile-web-friendly-privacy-for-ethereum-d02a8c400dad#5332

This quote is from the Hopper's official Medium page. 

In my understanding, EVM storage for each contract has 2^256 slots with 256 bit data per each slot, meanwhile Merkle Patricia tree storing storage data is created per each block.

1. Does the Merkle Patricia tree structure have influence on the limit of storage data for one contract ? 

2. When designing sustainable Dapps, should I be standing on the assumption that storage of a contract run out some day ?

I'd love to hear hints or advice to deepen my knowledge.

Thanks in advance.

**Comment by olivdb** [comment]
Hopper uses its own Merkle tree to store deposits. This is implemented in Solidity at the contract level and is different from the Merkle trees used internally by the Ethereum protocol.

**Comment by toshiboy86** [comment]
@olivdb 
Thank you so much.
